# Generated by Django 3.1.7 on 2021-05-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='landmark',
        ),
    ]
